[package]
name = "palabritas-parser"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "palabritas-parser"
path = "src/main.rs"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
rand = "0.8.5"
palabritas-common = { path = "../palabritas-common" }