[variables]
health = "integer"
time = "integer"
money = "integer"
donkey = "bool"
food = "integer"
time_mod = "integer"
energized = "float"
message = "string"
[variables.time_of_day]
enum = ["Day", "Night"]