[package]
name = "cuentitos-common"
version = "0.2.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.144", features = ["derive"] }
rmp-serde = "1.1.1"
rmp = "^0.8"
toml = "0.7.4"
typetag = "0.2"